[project]
name = "fork-sffcharaviewer"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.3.4",
    "pillow>=8.0.0",
    "pyinstaller>=4.0",
    "pyqt5>=5.15.0",
]

[tool.uv]
constraint-dependencies = ["pyqt5-qt5 <=5.15.2"]
